version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_transport_service
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run start:prod

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transport_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
